# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# Braintree configuration keys
BRAINTREE_MERCHANT_ID: 'b8wqbznzmq5mdqdp'
BRAINTREE_PUBLIC_KEY: 'fv4bwh56x29vkxrr'
BRAINTREE_PRIVATE_KEY: '0dc5a2d8a54c31debd6fe95ceac21db1'
